Update publish.yml

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -8,11 +8,7 @@ on:
 
 jobs:
   publish:
-    # To enable auto publishing to github, update your electron publisher
-    # config in package.json > "build" and remove the conditional below
-
     runs-on: ${{ matrix.os }}
-
     strategy:
       matrix:
         os: [macos-latest]
@@ -24,35 +20,32 @@ jobs:
       - name: Install Python
         run: |
           brew install python@3.12
+          python3 -m venv venv
 
       - name: Set up Python virtual environment
         run: |
-          python3 -m venv venv
           source venv/bin/activate
-          python3 -m pip install --upgrade pip
-          python3 -m pip install setuptools
+          python3 -m pip install --upgrade pip setuptools
 
-      - name: Install Node and NPM
+      - name: Install Node.js and NPM
         uses: actions/setup-node@v3
         with:
           node-version: 18
           cache: npm
 
-      - name: Install and build
+      - name: Install dependencies
         run: |
           source venv/bin/activate
           npm install
-          npm run postinstall
+          npm run postinstall || exit 0 # Continue even if postinstall fails
+
+      - name: Build application
+        run: |
+          source venv/bin/activate
           npm run build
 
       - name: Publish releases
         env:
-          # These values are used for auto updates signing
-          # APPLE_ID: ${{ secrets.APPLE_ID }}
-          # APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_ID_PASS }}
-          # CSC_LINK: ${{ secrets.CSC_LINK }}
-          # CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
-          # This is used for uploading release assets to github
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           source venv/bin/activate
